### ISSUE TITLE
Colors are not working

### ISSUE THREAD

**Issue by peri4n** [ojroques/nvim-hardline#1]
I see no colors in the status bar. Everything strays grey. Any idea of what could be the cause?

Running `:highlight` shows no hardline specific highlight group.

I am using the defautl configuration shown in the README.md

**Comment by ojroques** [comment]
Highlight groups are created in these lines: https://github.com/ojroques/nvim-hardline/blob/7a701bec8e78c9d30bea54a94475f46e90ce654f/lua/hardline.lua#L66-L78

Maybe the `ColorScheme` event is not triggered. I'll look into it.

**Comment by ojroques** [comment]
I've updated the plugin so that they are create on startup as well. Please tell me if it's still not working.

**Comment by peri4n** [comment]
Wow, that was quick!

Yes, it fixes it. Thank you very much!
