### ISSUE TITLE
[Question] Custom themes

### ISSUE THREAD

**Issue by kitallen23** [ojroques/nvim-hardline#21]
I'm hoping to implement my own theme, by customising the default one.

Is it at all possible to have custom configuration, and to source it via the options? For example:
```lua
require('hardline').setup {
  theme = './custom-default.lua'
}

```

Loving this plugin by the way!

**Comment by adisen99** [comment]
Made Pull request #19 for adding custom theme. Related to the issue. 

But in the PR, the setup options takes a custom colour table as input rather than a file.

**Comment by ojroques** [comment]
You can now pass a table to set a custom theme:
1. Set the `theme` option to `custom`
2. Pass the table with your colors to the `custom_theme` option.

Like so: (replace `NONE` by your color hex code e.g. `#98C379` ):
```lua
require('hardline').setup {
  theme = 'custom',   -- custom theme
  custom_theme = {
    text = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    normal = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    insert = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    replace = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    inactive_comment = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    inactive_cursor = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    inactive_menu = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    visual = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    command = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    alt_text = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
    warning = {gui = "NONE", cterm = "NONE", cterm16 = "NONE"},
  },
}
```

See #19. Thanks to @adisen99 for the feature.
