### ISSUE TITLE
Custom seperators?

### ISSUE THREAD

**Issue by blackCauldron7** [ojroques/nvim-hardline#22]
For example powerline seperators or semi circle seperators

**Comment by ojroques** [comment]
Do you mean for the bufferline? Yes there is an option for that:
```lua
require('hardline').setup {
  bufferline = true,
  bufferline_settings = {
      exclude_terminal = false,
      show_index = false,
      separator = '|',
  },
}
```
The README is not up-to-date, I'll update it asap sorry.

If you meant for the statusline, there's no single option for that but you can define your own statusline via the option table and insert the separator between each section yourself.

**Comment by blackCauldron7** [comment]
i meant for both and i was thinking of adding seperators myself maybe a color class separately of type seperator can be added?

**Comment by ojroques** [comment]
Not sure what you mean sorry. But feel free to submit a PR with your feature if you want :). In the meantime I'm closing this issue.
