### ISSUE TITLE
how can I display the lsp comption on command-line?

### ISSUE THREAD

**Issue by PHSix** [ojroques/nvim-hardline#5]
![图片](https://user-images.githubusercontent.com/57695072/107872677-ddf0a080-6ee6-11eb-9a9d-977457af9779.png)
I do not want it auto show lsp comption status in command-line. How can I display it?

**Comment by ojroques** [comment]
Not sure what you mean. If you're talking about `match 1 of 20` that's not from LSP.

If you want to disable LSP warning and error count, check [configuration](https://github.com/ojroques/nvim-hardline#configuration). You need to copy the `sections` options in your Neovim config and remove the lines related to LSP (those with `require('hardline.parts.lsp')`).

**Comment by PHSix** [comment]
![图片](https://user-images.githubusercontent.com/57695072/107875577-c7087900-6efb-11eb-99b6-8cbef5aa45d9.png)
Sorry, I didn’t express it clearly, I mean that it was always show the length of popupmenu on command-line like this, and I want it to not show.

**Comment by ojroques** [comment]
This is unrelated to nvim-hardline or the LSP client: it comes from Vim option `shortmess`. So to hide this message, try:

```
set shortmess=-c
```

I'm closing this issue, feel free to re-open it if needed.

**Comment by PHSix** [comment]
ok. Thank!

**Comment by PHSix** [comment]
I found that this information is displayed because you set the showmode option to false in `hardline.lua`.

**Comment by ojroques** [comment]
Yes I set it to False because the mode is already displayed in the statusline. When `showmode` is enabled, the mode is displayed in the command line and overrides all other messages . When the option is disabled, Vim can now show these messages `match 1 of ...` instead.
